// This file is generated by codegen, but it will only be generated once and will require manual modifications later.
//
// 注意：queryBinder 变量由本文件提供。若项目原有的 api.go 里还保留
// urlquerybinder 的 import 与 `var queryBinder = urlquerybinder.NewQueryBinder()`，
// 需要手动删除，否则会重复声明。

package api

import (
	"encoding"
	"fmt"
	"net/url"
	"reflect"
	"strconv"
	"strings"
)

// queryBinder 把 URL query 绑定到 spec 结构体。
//
// 与 urlquerybinder 之类的库不同，这里会展开匿名嵌入的字段，
// 因此 stores.PageSpec、stores.ModelSpec 里的 page/limit/skip/sort 等参数可以正常绑定；
// 取值时优先使用 encoding.TextUnmarshaler，其次兼容 andvari 约定的 Decode(string) error，
// 枚举类型（如 status=closed）因此可以直接使用文本值。
type queryBinderT struct {
	tag string
}

// stringDecoder 兼容 andvari 的 Decode(string) error 类型
type stringDecoder interface {
	Decode(string) error
}

var queryBinder = &queryBinderT{tag: "form"}

// SetTag 设置结构体参数标签名，空值忽略。
func (b *queryBinderT) SetTag(tag string) {
	if len(tag) > 0 {
		b.tag = tag
	}
}

// Bind 解析 u 的 query 参数并写入 obj，obj 必须是指向结构体的指针。
func (b *queryBinderT) Bind(obj any, u *url.URL) error {
	if u == nil {
		return nil
	}
	v := reflect.ValueOf(obj)
	if v.Kind() != reflect.Pointer || v.IsNil() || v.Elem().Kind() != reflect.Struct {
		return fmt.Errorf("queryBind: %T is not a struct pointer", obj)
	}
	return b.bindStruct(v.Elem(), u.Query())
}

func (b *queryBinderT) bindStruct(v reflect.Value, params url.Values) error {
	typ := v.Type()
	for i := 0; i < typ.NumField(); i++ {
		f := typ.Field(i)
		if len(f.PkgPath) > 0 && !f.Anonymous {
			continue // 非导出字段
		}
		fv := v.Field(i)
		if f.Anonymous {
			// 匿名嵌入的字段与父级共用命名空间
			ev := fv
			if ev.Kind() == reflect.Pointer {
				if ev.IsNil() {
					if !ev.CanSet() {
						continue
					}
					ev.Set(reflect.New(ev.Type().Elem()))
				}
				ev = ev.Elem()
			}
			if ev.Kind() == reflect.Struct {
				if err := b.bindStruct(ev, params); err != nil {
					return err
				}
				continue
			}
		}

		name, required := parseTagName(f.Tag.Get(b.tag))
		if len(name) == 0 {
			continue
		}
		vals, ok := params[name]
		if !ok || len(vals) == 0 {
			if required {
				return fmt.Errorf("queryBind: missing required param %q", name)
			}
			continue
		}
		if len(vals[0]) == 0 && !isStringKind(fv) {
			continue // 空值视为未提供
		}
		if err := b.setValue(fv, vals); err != nil {
			return fmt.Errorf("queryBind: param %q: %w", name, err)
		}
	}
	return nil
}

// parseTagName 解析 `name,required` 形式的标签，"-" 表示忽略。
func parseTagName(tag string) (string, bool) {
	name, opts, _ := strings.Cut(tag, ",")
	if name == "-" {
		return "", false
	}
	return name, strings.Contains(opts, "required")
}

func isStringKind(v reflect.Value) bool {
	if v.Kind() == reflect.Pointer {
		return v.Type().Elem().Kind() == reflect.String
	}
	return v.Kind() == reflect.String
}

func (b *queryBinderT) setValue(v reflect.Value, vals []string) error {
	if v.Kind() == reflect.Pointer {
		if v.IsNil() {
			v.Set(reflect.New(v.Type().Elem()))
		}
		return b.setValue(v.Elem(), vals)
	}
	if v.CanAddr() {
		switch tv := v.Addr().Interface().(type) {
		case encoding.TextUnmarshaler:
			return tv.UnmarshalText([]byte(vals[0]))
		case stringDecoder:
			return tv.Decode(vals[0])
		}
	}
	switch v.Kind() {
	case reflect.String:
		v.SetString(vals[0])
	case reflect.Bool:
		n, err := strconv.ParseBool(vals[0])
		if err != nil {
			return err
		}
		v.SetBool(n)
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		n, err := strconv.ParseInt(vals[0], 10, v.Type().Bits())
		if err != nil {
			return err
		}
		v.SetInt(n)
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		n, err := strconv.ParseUint(vals[0], 10, v.Type().Bits())
		if err != nil {
			return err
		}
		v.SetUint(n)
	case reflect.Float32, reflect.Float64:
		n, err := strconv.ParseFloat(vals[0], v.Type().Bits())
		if err != nil {
			return err
		}
		v.SetFloat(n)
	case reflect.Slice:
		sl := reflect.MakeSlice(v.Type(), 0, len(vals))
		for _, s := range vals {
			ev := reflect.New(v.Type().Elem()).Elem()
			if err := b.setValue(ev, []string{s}); err != nil {
				return err
			}
			sl = reflect.Append(sl, ev)
		}
		v.Set(sl)
	default:
		return fmt.Errorf("unsupported type %s", v.Type())
	}
	return nil
}
